from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import oracledb
import os
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="DimDim - API de Clientes",
    description="API para gerenciamento de clientes da DimDim (2º Checkpoint - DevOps & Docker)",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

DB_USER = os.getenv("DB_USER", "system")
DB_PASSWORD = os.getenv("DB_PASSWORD", "dimdim123")
DB_HOST = os.getenv("DB_HOST", "oracle-db")
DB_PORT = os.getenv("DB_PORT", "1521")
DB_SERVICE = os.getenv("DB_SERVICE", "XEPDB1")

DSN = f"{DB_HOST}:{DB_PORT}/{DB_SERVICE}"

def get_connection():
    return oracledb.connect(user=DB_USER, password=DB_PASSWORD, dsn=DSN)

def init_db():
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE '
                            CREATE TABLE clientes (
                                id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nome        VARCHAR2(100) NOT NULL,
                                email       VARCHAR2(150) NOT NULL UNIQUE,
                                cpf         VARCHAR2(14)  NOT NULL UNIQUE,
                                telefone    VARCHAR2(20),
                                saldo       NUMBER(15,2) DEFAULT 0,
                                ativo       NUMBER(1)    DEFAULT 1,
                                criado_em   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                            )
                        ';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE = -955 THEN NULL; END IF;
                    END;
                """)
                conn.commit()
                logger.info("Tabela verificada/criada com sucesso.")
    except Exception as e:
        logger.error(f"Erro ao inicializar banco: {e}")

@app.on_event("startup")
def startup_event():
    init_db()

class ClienteCreate(BaseModel):
    nome: str
    email: str
    cpf: str
    telefone: Optional[str] = None
    saldo: Optional[float] = 0.0

class ClienteUpdate(BaseModel):
    nome: Optional[str] = None
    email: Optional[str] = None
    telefone: Optional[str] = None
    saldo: Optional[float] = None
    ativo: Optional[int] = None

class ClienteOut(BaseModel):
    id: int
    nome: str
    email: str
    cpf: str
    telefone: Optional[str]
    saldo: float
    ativo: int
    criado_em: str

@app.get("/", tags=["Health"])
def root():
    return {"status": "ok", "app": "DimDim API", "version": "1.0.0"}

@app.get("/health", tags=["Health"])
def health():
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT 1 FROM DUAL")
        return {"status": "ok", "db": "connected"}
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"DB error: {e}")

@app.post("/clientes", response_model=ClienteOut, status_code=201, tags=["Clientes"])
def criar_cliente(cliente: ClienteCreate):
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    INSERT INTO clientes (nome, email, cpf, telefone, saldo)
                    VALUES (:nome, :email, :cpf, :telefone, :saldo)
                    RETURNING id, nome, email, cpf, telefone, saldo, ativo,
                              TO_CHAR(criado_em, 'YYYY-MM-DD HH24:MI:SS') INTO
                              :out_id, :out_nome, :out_email, :out_cpf,
                              :out_tel, :out_saldo, :out_ativo, :out_criado
                """,
                dict(
                    nome=cliente.nome, email=cliente.email, cpf=cliente.cpf,
                    telefone=cliente.telefone, saldo=cliente.saldo,
                    out_id=cur.var(int), out_nome=cur.var(str),
                    out_email=cur.var(str), out_cpf=cur.var(str),
                    out_tel=cur.var(str), out_saldo=cur.var(float),
                    out_ativo=cur.var(int), out_criado=cur.var(str)
                ))
                conn.commit()
                row = cur.bindvars
                return ClienteOut(
                    id=row["out_id"].getvalue()[0],
                    nome=row["out_nome"].getvalue()[0],
                    email=row["out_email"].getvalue()[0],
                    cpf=row["out_cpf"].getvalue()[0],
                    telefone=row["out_tel"].getvalue()[0],
                    saldo=float(row["out_saldo"].getvalue()[0] or 0),
                    ativo=int(row["out_ativo"].getvalue()[0]),
                    criado_em=row["out_criado"].getvalue()[0]
                )
    except oracledb.IntegrityError as e:
        raise HTTPException(status_code=409, detail=f"CPF ou e-mail já cadastrado: {e}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/clientes", tags=["Clientes"])
def listar_clientes():
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT id, nome, email, cpf, telefone, saldo, ativo,
                           TO_CHAR(criado_em, 'YYYY-MM-DD HH24:MI:SS')
                    FROM clientes ORDER BY id
                """)
                rows = cur.fetchall()
                return [
                    ClienteOut(id=r[0], nome=r[1], email=r[2], cpf=r[3],
                               telefone=r[4], saldo=float(r[5] or 0),
                               ativo=int(r[6]), criado_em=r[7])
                    for r in rows
                ]
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/clientes/{cliente_id}", response_model=ClienteOut, tags=["Clientes"])
def buscar_cliente(cliente_id: int):
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT id, nome, email, cpf, telefone, saldo, ativo,
                           TO_CHAR(criado_em, 'YYYY-MM-DD HH24:MI:SS')
                    FROM clientes WHERE id = :id
                """, [cliente_id])
                row = cur.fetchone()
                if not row:
                    raise HTTPException(status_code=404, detail="Cliente não encontrado")
                return ClienteOut(id=row[0], nome=row[1], email=row[2], cpf=row[3],
                                  telefone=row[4], saldo=float(row[5] or 0),
                                  ativo=int(row[6]), criado_em=row[7])
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.put("/clientes/{cliente_id}", response_model=ClienteOut, tags=["Clientes"])
def atualizar_cliente(cliente_id: int, dados: ClienteUpdate):
    campos = {k: v for k, v in dados.dict().items() if v is not None}
    if not campos:
        raise HTTPException(status_code=400, detail="Nenhum campo para atualizar.")
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                sets = ", ".join(f"{k} = :{k}" for k in campos)
                campos["id"] = cliente_id
                cur.execute(f"UPDATE clientes SET {sets} WHERE id = :id", campos)
                if cur.rowcount == 0:
                    raise HTTPException(status_code=404, detail="Cliente não encontrado")
                conn.commit()
        return buscar_cliente(cliente_id)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.delete("/clientes/{cliente_id}", tags=["Clientes"])
def deletar_cliente(cliente_id: int):
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("DELETE FROM clientes WHERE id = :id", [cliente_id])
                if cur.rowcount == 0:
                    raise HTTPException(status_code=404, detail="Cliente não encontrado")
                conn.commit()
        return {"message": f"Cliente {cliente_id} removido com sucesso."}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))